- .eslintignore
- .eslintrc.json
- package.json
- yarn.lock
Closes: [RA-7](https://react-adventures.atlassian.net/browse/RA-7)
> RA-7: add eslint

- .prettierignore
- babel.config.js
- package.json
- webpack.config.js
- yarn.lock
Closes: [RA-8](https://react-adventures.atlassian.net/browse/RA-8)
> RA-8: add webpack

- babel.config.js
- package.json
- src/App.tsx
- src/modules/mainScreen/containers/counter/actions.ts
- src/modules/router/actions.ts
- src/modules/router/routerSaga.ts
- src/store/index.ts
- src/store/rootSaga.ts
- yarn.lock
Closes [RA-6](https://react-adventures.atlassian.net/browse/RA-6)
> RA-6: add Redux-saga

- .eslintrc.js
- @types/assets/index.d.ts
- @types/global/index.d.ts
- package.json
- src/modules/mainScreen/index.tsx
- src/modules/router/Router.tsx
- src/modules/router/constants.ts
- src/modules/sprites/containers/SpritesGeneratorContainer.tsx
- src/modules/sprites/hooks/useCanvas.tsx
- src/modules/sprites/hooks/useKeyframes.tsx
- src/modules/sprites/utils/download-image.ts
- tsconfig.json
- yarn.lock
Closes: [RA-12](https://react-adventures.atlassian.net/browse/RA-12)
> RA-12: add sprite generator

- .eslintrc.js
- src/modules/battlefield/components/Battlefield/index.tsx
- src/modules/battlefield/components/HealthBar/index.tsx
- src/modules/battlefield/components/HealthBar/styled.ts
- src/modules/battlefield/constants.ts
- src/modules/battlefield/helpers/checkMeleeAttackConstraints.ts
- src/modules/battlefield/helpers/getRandomNumberInRange.ts
- src/modules/battlefield/reducers/troopsSlice.ts
- src/modules/battlefield/sagas/attackSaga.ts
- src/modules/battlefield/sagas/cursorSaga.ts
- src/modules/battlefield/sagas/roundSaga.ts
- src/modules/battlefield/sagas/supportSaga.ts
- src/modules/battlefield/selectors.ts
- src/modules/battlefield/types.ts
Closes: [RA-13](https://react-adventures.atlassian.net/browse/RA-13)
> RA-13: add attack

- src/modules/battlefield/components/Battlefield/index.tsx
- src/modules/battlefield/components/Battlefield/styled.ts
- src/modules/battlefield/containers/BattlefieldContainer.tsx
Closes: [RA-16](https://react-adventures.atlassian.net/browse/RA-16)
> RA-16: add highlighter

- src/modules/animation/containers/CharacterAnimation.tsx
- src/modules/animation/troopersAnimationInstances.ts
- src/modules/battlefield/constants.ts
- src/modules/battlefield/containers/TileContainer/index.tsx
- src/modules/battlefield/reducers/roundSlice.ts
- src/modules/battlefield/sagas/attackSaga.ts
- src/modules/battlefield/sagas/roundSaga.ts
Closes: [RA-20](https://react-adventures.atlassian.net/browse/RA-20)
> RA-20: add melee trooper attack animations

- src/modules/battlefield/helpers/checkMeleeAttackConstraints.ts
Closes: [RA-31](https://react-adventures.atlassian.net/browse/RA-31)
> RA-31: fix melee constraints

- src/GlobalStyle.ts
- src/modules/mainScreen/components/MainTitle/index.tsx
- src/modules/mainScreen/components/MainTitle/styled.tsx
- src/modules/mainScreen/components/Options/index.tsx
- src/modules/mainScreen/components/Options/styled.tsx
- src/modules/mainScreen/index.tsx
- src/modules/mainScreen/styled.tsx
Closes: [RA-19](https://react-adventures.atlassian.net/browse/RA-19)
> RA-19: add main screen

- src/common/helpers/getRandomArrayElement.ts
- src/common/helpers/index.ts
- src/modules/animation/containers/CharacterAnimation.tsx
- src/modules/animation/troopersAnimationInstances.ts
- src/modules/battlefield/constants.ts
- src/modules/battlefield/helpers/getCharacterProps.ts
- src/modules/battlefield/sagas/AISaga/index.ts
- src/modules/battlefield/sagas/AISaga/strategicAI.ts
- src/modules/battlefield/sagas/attackSaga.ts
- src/modules/wardrobe/constants.ts
Closes: [RA-34](https://react-adventures.atlassian.net/browse/RA-34) and [RA-36](https://react-adventures.atlassian.net/browse/RA-36)
> RA-34: fix damage obtaining

- src/GlobalStyle.ts
- src/modules/animation/containers/CharacterAnimation.tsx
- src/modules/animation/troopersAnimationInstances.ts
- src/modules/battlefield/actions.ts
- src/modules/battlefield/constants.ts
- src/modules/battlefield/containers/BattlefieldContainer/index.tsx
- src/modules/battlefield/containers/TileContainer/index.tsx
- src/modules/battlefield/containers/UserInterfaceContainer/hooks/useImages.ts
- src/modules/battlefield/containers/UserInterfaceContainer/index.tsx
- src/modules/battlefield/containers/UserInterfaceContainer/styled.ts
- src/modules/battlefield/reducers/battlefieldLoadedStatusSlice.ts
- src/modules/battlefield/reducers/index.ts
- src/modules/battlefield/sagas/initSaga.ts
- src/modules/battlefield/sagas/roundSaga.ts
- src/modules/battlefield/selectors.ts
- src/store/rootSaga.ts
Closes: [RA-21](https://react-adventures.atlassian.net/browse/RA-21)
> RA-21: add trooper ui

- public/archer.scon
- src/modules/animation/containers/CharacterAnimation.tsx
- src/modules/battlefield/constants.ts
- src/modules/battlefield/sagas/AISaga/index.ts
- src/modules/battlefield/sagas/AISaga/randomAI.ts
- src/modules/battlefield/sagas/AISaga/strategicAI.ts
- src/modules/battlefield/sagas/attackSaga.ts
- src/modules/battlefield/sagas/roundSaga.ts
- src/modules/battlefield/types.ts
Closes: [RA-25](https://react-adventures.atlassian.net/browse/RA-25)
> RA-25: add critical strike

- src/modules/battlefield/sagas/attackSaga.ts
- src/modules/battlefield/sagas/roundSaga.ts
- src/modules/battlefield/types.ts
Closes: [RA-39](https://react-adventures.atlassian.net/browse/RA-39)
> RA-39: fix disabled battlefield status

- src/modules/battlefield/actions.ts
- src/modules/battlefield/constants.ts
- src/modules/battlefield/containers/UserInterfaceContainer/containers/DamageIndicator/index.tsx
- src/modules/battlefield/containers/UserInterfaceContainer/containers/styled.ts
- src/modules/battlefield/containers/UserInterfaceContainer/index.tsx
- src/modules/battlefield/reducers/damageEventsSlice.ts
- src/modules/battlefield/reducers/hoveredElementSlice.ts
- src/modules/battlefield/reducers/index.ts
- src/modules/battlefield/reducers/troopsSlice.ts
- src/modules/battlefield/sagas/attackSaga.ts
- src/modules/battlefield/sagas/damageEventsSaga.ts
- src/modules/battlefield/sagas/roundSaga.ts
- src/modules/battlefield/selectors.ts
- src/store/rootSaga.ts
Closes: [RA-37](https://react-adventures.atlassian.net/browse/RA-37)
> RA-37: display damage effect

- src/modules/battlefield/sagas/AISaga/determinedAI.ts
- src/modules/battlefield/sagas/AISaga/randomAI.ts
- src/modules/battlefield/sagas/AISaga/strategicAI.ts
Closes: [RA-33](https://react-adventures.atlassian.net/browse/RA-33)
> RA-33: add block to AI turns

- src/modules/battlefield/actions.ts
- src/modules/battlefield/helpers/getCharacterProps.ts
- src/modules/battlefield/reducers/troopsSlice.ts
- src/modules/battlefield/sagas/attackSaga.ts
- src/modules/battlefield/sagas/effectsSaga/effects/poison.ts
Closes: [RA-54](https://react-adventures.atlassian.net/browse/RA-54)
> RA-54: fix poison effect in case it kills the target

- src/modules/battlefield/constants.ts
- src/modules/battlefield/sagas/effectsSaga/effects/anchor.ts
- src/modules/battlefield/sagas/effectsSaga/index.ts
- src/modules/battlefield/types.ts
closes: [RA-56](https://react-adventures.atlassian.net/browse/RA-56)
> RA-56: fix anchor effect 

- .eslintrc.js
- src/common/components/Dialog/Border.tsx
- src/common/components/Dialog/Header.tsx
- src/common/components/Dialog/Spots.tsx
- src/common/components/Dialog/index.tsx
- src/common/components/Dialog/styled.ts
- src/common/helpers/raise.ts
- src/common/hooks/useEventListener.ts
- src/common/hooks/useKeyPress.ts
- src/modules/battlefield/containers/BattlefieldContainer/index.tsx
- src/modules/battlefield/containers/UserInterfaceContainer/components/Info/styled.ts
Closes: [RA-41](https://react-adventures.atlassian.net/browse/RA-41)
> RA-41: add dialog

- src/modules/battlefield/containers/BattlefieldContainer/index.tsx
- src/modules/battlefield/containers/BattlefieldContainer/styled.ts
- src/modules/battlefield/containers/TileContainer/index.tsx
- src/modules/battlefield/sagas/roundSaga.ts
- src/store/rootSaga.ts
Closes: [RA-42](https://react-adventures.atlassian.net/browse/RA-42)
> RA-42: fix click on ally, or dead trooper

- .eslintrc.js
- paths.js
- src/common/constants.ts
- src/common/helpers/equipment.ts
- src/common/types/Character.ts
- src/common/types/index.ts
- src/configs/armors.ts
- src/configs/helmets.ts
- src/configs/swords.ts
- src/configs/weapons.ts
- src/modules/animation/containers/CharacterAnimation.tsx
- src/modules/animation/troopersAnimationInstances.ts
- src/modules/battlefield/constants.ts
- src/modules/battlefield/containers/BattlefieldContainer/index.tsx
- src/modules/battlefield/containers/TileContainer/index.tsx
- src/modules/battlefield/helpers/getCharacterProps.ts
- src/modules/battlefield/sagas/abilitiesSaga/abilities/might.ts
- src/modules/battlefield/sagas/bloodSaga.ts
- src/modules/battlefield/sagas/effectsSaga/effects/poison.ts
- src/modules/battlefield/types.ts
- src/modules/wardrobe/constants.ts
- src/modules/wardrobe/containers/WardrobeContainer/index.tsx
- webpack.config.js
Closees: [RA-61](https://react-adventures.atlassian.net/browse/RA-61)
> RA-61: add equipment visualization

- src/common/constants.ts
- src/common/helpers/applyDefenceAndResistance.ts
- src/common/types/Character.ts
- src/factory/characters/goblins.ts
- src/factory/characters/hero.ts
- src/factory/characters/mages.ts
- src/factory/characters/mountain-warriors.ts
- src/factory/characters/priests.ts
- src/factory/staffs.ts
- src/modules/battlefield/sagas/attackSaga.ts
- src/modules/battlefield/sagas/effectsSaga/effects/poison.ts
Closes [RA-69](https://react-adventures.atlassian.net/browse/RA-69)
> RA-69: add damage type and resistance

- README.md
Closes: [RA-71](https://react-adventures.atlassian.net/browse/RA-71)
> RA-71: add battlefield docs

- src/modules/battlefield/sagas/abilitiesSaga/README.md
Closes: [RA-72](https://react-adventures.atlassian.net/browse/RA-72)
> RA-72: add abilities and effects docs

- src/common/types/Character.ts
- src/modules/battlefield/sagas/attackSaga.ts
Closes: [RA-79](https://react-adventures.atlassian.net/browse/RA-79)
> RA-79: add melee counter attack

- src/common/containers/InventoryDialogContainer.tsx
- src/common/hooks/useDialogActions.ts
- src/modules/battlefield/containers/TileContainer/index.tsx
- src/modules/dialogs/actions.ts
- src/modules/dialogs/constants/dialogTypes.ts
- src/modules/dialogs/constants/index.ts
- src/modules/dialogs/containers/DialogsContainer.tsx
- src/modules/dialogs/helpers/getDialogByType.ts
- src/modules/dialogs/helpers/registerDialog.ts
- src/modules/dialogs/initializers/registerDialogs.ts
- src/modules/dialogs/reducers/dialogsSlice.ts
- src/modules/dialogs/reducers/index.ts
- src/modules/dialogs/registered-dialogs.ts
- src/modules/dialogs/selectors.ts
- src/modules/router/Router.tsx
- src/store/rootReducer.ts
Closes: [RA-45](https://react-adventures.atlassian.net/browse/RA-45)
> RA-45: add Dialog API

- src/common/components/Dialog/styled.ts
- src/common/constants.ts
- src/common/types/Character.ts
- src/modules/battlefield/dialogs/CharacterDetailsDialogContainer/components/Abilities/index.tsx
- src/modules/battlefield/dialogs/CharacterDetailsDialogContainer/components/Effects/index.tsx
- src/modules/battlefield/dialogs/CharacterDetailsDialogContainer/components/Effects/styled.ts
- src/modules/battlefield/dialogs/CharacterDetailsDialogContainer/index.tsx
- src/modules/battlefield/sagas/effectsSaga/effects/anchor.ts
- src/modules/battlefield/sagas/effectsSaga/effects/bleeding.ts
- src/modules/battlefield/sagas/effectsSaga/effects/block.ts
- src/modules/battlefield/sagas/effectsSaga/effects/continuesHeal.ts
- src/modules/battlefield/sagas/effectsSaga/effects/hex.ts
- src/modules/battlefield/sagas/effectsSaga/effects/might.ts
- src/modules/battlefield/sagas/effectsSaga/effects/poison.ts
- src/modules/battlefield/sagas/effectsSaga/effects/weakness.ts
Closes: [RA-89](https://react-adventures.atlassian.net/browse/RA-89)
> RA-89: Add effect to info dialog
